In [47]:



import numpy as np
from tensorflow.keras.models import load_model
from keras.preprocessing.image import img_to_array
import cv2

In [49]:
face_classifier=cv2.CascadeClassifier("C:\\Users\\lenovo\\Downloads\\haarcascade_frontalface_default.xml")

In [51]:
classifier=load_model("emotionRecognition.h5")


In [ ]:
labels=["angry","happy","sad","surprised"]
cap=cv2.VideoCapture(0)
while True:
    _,frame=cap.read()
    frame=cv2.flip(frame,1)
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces=face_classifier.detectMultiScale(gray)
    for(x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h), (0,255,255),2)
        face_gray=gray[y:y+h,x:x+w]
        face_gray = cv2.resize(face_gray, (48,48), interpolation=cv2.INTER_AREA)
        if np.sum([face_gray])!=0:
            face_normalized = face_gray.astype('float')/255.0
            face_normalized=img_to_array(face_normalized)
            face_normalized = np.expand_dims(face_normalized, axis=0) # to convert 48*48 to 1*48*48
            prediction = classifier.predict(face_normalized)[0]
            print(prediction)  # Check if probabilities favor "happy" significantly

            label=labels[prediction.argmax()]
            label_position = (x,y-10)
            cv2.putText(frame,label, label_position,cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),2)
        else:
            cv2.putText(frame, 'No Faces', (30,80),cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),2)

    cv2.imshow('Emotion Detector', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
        

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step
[0.41307655 0.29991448 0.28070062 0.00630842]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[0.41309053 0.2996233  0.28099063 0.0062955 ]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
[0.4131511  0.29956874 0.28098354 0.00629665]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[0.41289997 0.29976732 0.28103387 0.00629884]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[0.41277698 0.2999093  0.2810108  0.00630292]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[0.41272664 0.29988232 0.28108305 0.00630793]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[0.41295168 0.29992583 0.28081366 0.00630876]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[0.4131672  0.299764   0.28075576 0.00631303]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[0.41292274 0.2999478  0.2808179  0.00631153]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[0.4133993  0.29955396 0.28074023 0.0063065 ]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[0.41316658 0.29966706 0.28085607 0.00631027]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
[0.41319817 0.29973462 0.28075385 0.0